export type {
  ActiveService,
  Appointment,
  ClinicQueueStatus,
  Diagnosis,
  Gender,
  ImagingResult,
  InsuranceCard,
  LabResult,
  Patient,
  PatientSummary,
  Prescription,
  PrescriptionItem,
  Registration,
  Service,
  TodayVisitStatus,
  Visit,
  VisitDetail,
  VitalSigns,
} from "@anphu/patient-domain";
